contentDir = "/Users/admin/Documents/git/vlp/vlpstatisch2/vlphugo/content/post/"
publishDir = "/Users/admin/Documents/git/vlp/vlpstatisch2/vlphugo/public/"
layoutDir = "/Users/admin/Documents/git/vlp/vlpstatisch2/vlphugo/layouts/"
publishDrafts = false
disableRSS = true
disableSitemap = true
disable404 = true
baseurl = ""
languageCode = "de-de"
title = "VLP Hugo"
